# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openach', '0031_auto_20161004_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSourceScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsafe', models.NullBooleanField()),
                ('last_scan', models.DateTimeField()),
                ('cache_deadline', models.DateTimeField()),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safescan', to='openach.EvidenceSource')),
            ],
        ),
    ]
